- name: Demo on vars play level
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Demo on vars on task level
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL {{ URL }}
      vars:
        URL: task.example.com

- name: Demo on vars from file on play level
  hosts: localhost
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL {{ URL }}

- name: Vars from Inventory file
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
- name: Acces fact
  hosts: localhost
  gather_facts: false
    tasks:
      - name: Print FACT
        ansible.builtin.debug:
          msg: Hostname = {{ ansible_hostname }}